version: '3.8'

services:
  # Aplicação PHP/Symfony
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env          # sempre carregado
      - .env.local    # sobrescreve variáveis do .env
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - symfony_network
    depends_on:
      - db
      - redis

  # Servidor Web (Nginx)
  webserver:
    image: nginx:1.25.3-alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    depends_on:
      - app

  # Banco de dados MySQL
  db:
    image: mysql:8.0.35 
    container_name: symfony_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  # Redis para cache/sessões
  redis:
    image: redis:7.2.3-alpine  
    container_name: symfony_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
